version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
      - JWT_SECRET=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImFkbWluIjp0cnVlfQ.zrpma4yJzkhUvFO0c-EZ_Li-fw7mSBdAN9iH2Jdm8xwHvaC-3uvwcpihzv5uvr7PiAvP2A7cTRcXob1Ioad7mQ
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5.0
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge